### ISSUE TITLE
Poison dependency for Phoenix 1.4

### ISSUE THREAD

**Issue by stuartbain** [danschultzer/pow_assent#14]
I get the following error message when adding pow_assent as a dependency in a Phoenix 1.4 application:

`warning: function Poison.decode!/1 is undefined (module Poison is not available)
  lib/pow_assent/strategies/azure_oauth2.ex:97`

Poison has been replaced by Jason as a dependency in Phoenix 1.4 and so mix needs to specifically include it as a dependency for Phoenix 1.4 users.

**Comment by danschultzer** [comment]
Thanks! I've opened #21 to fix it. Still some work to do, as the oauth2 library I use uses global configuration for serializers and depends on Poison by default.
