### ISSUE TITLE
Consider changing Google strategy urls

### ISSUE THREAD

**Issue by stuartbain** [danschultzer/pow_assent#16]
The current Google strategy configuration urls use the Google Plus endpoint. This requires the enabling of the Google+ api on the Google Cloud platform in addition to setting up the application keys.

I have overridden the configuration settings as follows:

```
config :my_app, :pow_assent,
  providers: [
    google: [
      client_id: System.get_env("GOOGLE_CLIENT_ID"),
      client_secret: System.get_env("GOOGLE_CLIENT_SECRET"),
      strategy: PowAssent.Strategy.Google,
      site: "https://www.googleapis.com",
      token_url: "https://www.googleapis.com/oauth2/v4/token",
      authorize_url: "https://accounts.google.com/o/oauth2/v2/auth",
      user_url: "/oauth2/v3/userinfo"
    ]
  ]

```

This provides the same info as the Google Plus endpoint but doesn't require any additional APIs to be enabled on Google Cloud Platform.

**Comment by stuartbain** [comment]
Interestingly, I had to modify the pattern matching on:

```
defp verified_email(%{"email_verified" => "true"} = user), do: user["email"]
```

to

```
defp verified_email(%{"email_verified" => true} = user), do: user["email"]
```

**Comment by danschultzer** [comment]
Cool, thanks! I think this was added after sunsetting of google plus was announced. I'll update the strategy.

**Comment by jhefreyzz** [comment]
@danschultzer may I know if this issue has been fixed in the current release?

**Comment by danschultzer** [comment]
No, you should pull from the master branch directly:

```elixir
{:pow_assent, github: "danschultzer/pow_assent"}
```

I'll release a new version once #14 has been resolved.
