### ISSUE TITLE
Multiple providers workflow for signed out user

### ISSUE THREAD

**Issue by stuartbain** [danschultzer/pow_assent#18]
When a signed in user adds a new sign in provider via /auth/:provider/new, they are correctly added to the user_identities table and linked to the logged in user id.

However, consider the following scenario where a logged out user attempts to login using a new authentication provider:

1. New user registers using Facebook as authentication provider. User is created with email address user1@example.com
2. User signs out
3. User attempts to login using Google as authentication provider which has the same e-mail address as associated with their Facebook account (user1@example.com)
4. Currently, the user is prompted to provide an e-mail address (user1@example.com) on the add_user registration form which then fails with an email "has already been taken" error because there is already a user with an email user1@example.com

I want to ensure that a user should only be able to link a new authentication provider when they are already logged in as a user with the same email address. However I would like to be able to let the user know that there is already an account with this e-mail and offer to link them once they authenticate successfully.

Is this possible?

**Comment by danschultzer** [comment]
You have two options; build a custom authorization controller or changes how `MyApp.UserIdentities.create_user/4` works.

The latter is the easier one as you would only need to override/add `MyApp.UserIdentities.create_user/4` method to your user identity context module. You have to be aware that this could potentially open up security flaws. In this case we'll check by using `params` that comes from the provider. `user_id_params` are provided by the user in case the user id has already been taken.

```elixir
def create_user(provider, uid, params, user_id_params) do
  case Users.get_user_by_email(params["email"]) do
    user -> user
    nil -> pow_assent_create_user(provider, uid, params, user_id_params)
  end
end
```

Creating a custom controller is far more complex as you also have to work around the plug methods. It would give you much better control over security though.

Ultimately, I think that by default requiring users to authenticate before they can add a second authentication to their account is the proper way of handling security.

**Comment by danschultzer** [comment]
Oh wait, sorry, I completely misread your question 😄

**Comment by danschultzer** [comment]
So I assume you'll show a screen with two options. Sign in to link, or create with new email?

This could be done with a custom controller. Very rough idea of how it could look:

```elixir
scope "/" do
  pipe_through :browser

  pow_routes()

  scope "/auth", as: "pow_assent" do
    resources "/:provider", PowAssent.Phoenix.AuthorizationController, singleton: true, only: [:new, :delete]
    get "/:provider/callback", PowAssent.Phoenix.AuthorizationController, :callback

    get "/:provider/add-user-id", MyAppWeb.UserIdentityRegistrationController, :add_user_id
    post "/:provider/link", MyAppWeb.UserIdentityRegistrationController, :link
    post "/:provider/create", PowAssent.Phoenix.RegistrationController, :create
  end
end
```

```elixir
defmodule MyAppWeb.UserIdentityRegistrationController do
  use MyAppWeb, :controller

  def add_user_id(conn, _params) do
    case user_with_email_exists?(conn.private[:pow_assent_params]) do
       true ->
          changeset = Pow.Plug.change_user(conn, %{"email" => conn.private[:pow_assent_params]["email"]})

          render(conn, "add_user_id.html", changeset: changeset)

      false ->
        Pow.Phoenix.RegistrationController.add_user_id(conn, params)
    end
  end

  def link(conn, %{"provider" => provider, "user" => user_params}) do
    case link_user(conn, provider, user_params)
      {:ok, conn} ->
        PowAssent.Phoenix.AuthorizationController.routes(conn).after_sign_in_path(conn)

      {:error, conn} ->
        render(conn, "add_user_id.html", changeset: Plug.change_user(conn, user_params))
    end
  end

  defp user_with_email_exists?(params), do: # Check if user with email already exists

  defp link_user(conn, user_params) do
    conn
    |> Plug.authenticate_user(user_params)
    |> case do
      {:ok, conn} ->
        uid = conn.private[:pow_assent_params]["uid"]
        user = Pow.Plug.current_user(conn)
        config = Pow.Plug.fetch_config(conn)

        conn
        |> Pow.Plug.current_user()
        |> PowAssent.Operations.create(provider, uid, config)
        |> case do
          {:ok, _user_identity} -> {:ok, user, conn}
          {:error, changeset}   -> {:error, changeset, conn}
        end

      {:error, conn} ->
        {:error, conn}
    end
  end
end
```

The `add_user_id.html.eex` template has two options, the original add new user id form, and then one is a sign in form that posts to `Routes.pow_assent_registration_path(conn, :link)`.

**Comment by stuartbain** [comment]
That's a great help Dan. I'm trying to replicate the type of workflow that Gravatar uses to link additional authentication providers to an existing account that matches on the e-mail address. See screenshot below. 

<img width="489" alt="screenshot 2018-11-14 at 09 36 05" src="https://user-images.githubusercontent.com/1169602/48730594-ce644d80-ec32-11e8-8491-c1efa9b2ac1b.png">

I was working my way through the custom controllers guide for Pow but this gets me most of the way there. Thanks for the super quick response and code example.

**Comment by danschultzer** [comment]
Sounds good! I think this could be good to have as a guide too, so if you're willing to post some sample code when you get it working that would be great.
