### ISSUE TITLE
does the Pow, Pow Assent, Phoenix Oauth2 Provider provide all the config I need for a Pow Assent Oauth2 strategy

### ISSUE THREAD

**Issue by niccolox** [danschultzer/pow_assent#29]
I have a provider running Pow, Pow Assent and Phoenix Oauth2 Provider
provider http://localhost:4453

I have a client running Pow and Pow Assent
client http://localhost:4913

both are setup in the standard README way

in the client I have Pow Assent like this

```
config :test_com, :pow_assent,
       providers:
         [
           test_com: [
             client_id: "redacted",
             client_secret: "redacted",
             strategy: PowAssent.Strategy.OAuth2,
             authorization_params: [scope: "user:read user:write"],
             site: "http://localhost:4453"
           ]
         ]
```

on the provider I have /oauth/applications setup like this

callback 
http://localhost:4913/auth/test_com/callback/

I get an error when I try to authorize

the github strategy works fine

**does the Pow, Pow Assent, Phoenix Oauth2 Provider provide all the config I need for a Pow Assent Oauth2 strategy or do I need extra code or config to handle adding users?**

**Comment by danschultzer** [comment]
I'm going to test this but seems like state is not carried over: https://github.com/danschultzer/phoenix_oauth2_provider/issues/15

**Comment by danschultzer** [comment]
So your issue is just that you have a CSRF check for the oauth routes. This doesn't work because there's a token POST endpoint. The solution is to just remove `:protect_from_forgery` from the pipeline.

**Comment by niccolox** [comment]
thanks for the help, made some progress, but not there
am going to do more oauth2 background research
I think I have a basic oauth2 awareness problem which is snagging me on each integration/troubleshooting step

**Comment by danschultzer** [comment]
Ah I see. I did answer in detail how you can solve your issue in https://github.com/danschultzer/phoenix_oauth2_provider/issues/15, but for general outh2 understanding I recommend this article: https://aaronparecki.com/oauth-2-simplified/

DigitalOcean’s community article is also useful: https://www.digitalocean.com/community/tutorials/an-introduction-to-oauth-2
