### ISSUE TITLE
Incorrect console instructions when generating templates?

### ISSUE THREAD

**Issue by dottjt** [danschultzer/pow_assent#30]
Hi!

When I go to generate the POW Assent templates, it shows this message in the console:

`Please set web_module: NfdWeb in your configuration.

    defmodule NfdWeb.Endpoint do
      use NfdWeb.Endpoint, otp_app: :nfd

      # ...

      plug NfdWeb.Pow.Plug.Session,
        repo: Nfd.Repo,
        user: Nfd.Users.User,
        web_module: NfdWeb

      # ...
    end`

The only issue is that with the first line change (use NfdWeb.Endpoint, otp_app: :nfd) I get this error:

`** (CompileError) lib/nfd_web/endpoint.ex:60: you are trying to use the module NfdWeb.Endpoint which is currently being defined.`

and then it goes to say that `plug NfdWeb.Pow.Plug.Session` doesn't exist. 

What would be the solution in this case?

I know as part of the original POW setup there's this piece of code:
`
  plug Pow.Plug.Session, 
    otp_app: :nfd
`

Would I essentially just append everything to that as opposed to `plug NfdWeb.Pow.Plug.Session`?

Thank you so much in advance :)

**Comment by danschultzer** [comment]
Oh thanks! It should be `use Phoenix.Endpoint` not `use NfdWeb.Endpoint`, so it should look like this:

```elixir
defmodule NfdWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :nfd

  # ...

  plug NfdWeb.Pow.Plug.Session,
    repo: Nfd.Repo,
    user: Nfd.Users.User,
    web_module: NfdWeb

  # ...
end
```

I'll add a fix for it right away.

**Comment by danschultzer** [comment]
And yeah, you should use `Pow.Plug.Session` not `NfdWeb.Pow.Plug.Session`. I should have caught this before.

**Comment by danschultzer** [comment]
By the way, if you have the config setup:

```elixir
config :my_app, :pow,
  user: MyApp.Users.User,
  repo: MyApp.Repo
```

Then you should just add the `:web_module` there, and keep the `plug Pow.Plug.Session, otp_app: :my_app` as I imagine it was previously.

**Comment by dottjt** [comment]
Thank you so much! You've made my day, and I just want to say, thank you THANK YOU so much for all the work you've put towards this library. It is honestly invaluable to the Elixir community :)

**Comment by danschultzer** [comment]
Thank you for the kind words @dottjt! 😄
