### ISSUE TITLE
Can't get custom messages to work

### ISSUE THREAD

**Issue by jonathanraes** [danschultzer/pow_assent#45]
Hi, 

Im trying to create a flash message to show users on sign in, this is my Pow.Messages module.
```
defmodule MyApp.Pow.Messages do
  use Pow.Phoenix.Messages
  use Pow.Extension.Phoenix.Messages,
    extensions: [PowAssent, PowResetPassword, PowEmailConfirmation]

  import MyAppWeb.Gettext

  def signed_in(conn), do: gettext("Welcome, %{name}", name: conn.assigns.current_user.name)

  def pow_assent_signed_in(_conn, provider), do: gettext("You've been signed in with %{provider}.", provider: provider)
```

When a user logs in using the email:password combination, a message appears. However, nothing appears when the social sign in option is used. Is there something I'm missing?

**Comment by danschultzer** [comment]
Have you set the messages in your config?

```elixir
config :my_app, :pow,
  # ...
  messages_backend: MyApp.Pow.Messages
```

It was missing from the readme, but I've updated it.

**Comment by jonathanraes** [comment]
I have set the messages in my config, yes.

What I forgot to mention though was that running `mix pow.extension.phoenix.gen.templates --extension PowAssent` failed with the error message:
 `No extensions was provided as arguments, or found in 'config :my_app, :pow' configuration.` 

I don't have PowAssent in the `extensions` part of my config, I tried adding it but that didn't work.

My full config  section:
```
config :my_app, :pow,
  user: MyApp.Users.User,
  repo: MyApp.Repo,
  web_module: MyAppWeb,
  mailer_backend: MyAppWeb.PowMailer,
  messages_backend: MyAppWeb.Pow.Messages,
  routes_backend: MyAppWeb.Pow.Routes,
  extensions: [PowResetPassword, PowEmailConfirmation],
  controller_callbacks: Pow.Extension.Phoenix.ControllerCallbacks
```

**Comment by danschultzer** [comment]
> What I forgot to mention though was that running mix pow.extension.phoenix.gen.templates --extension PowAssent failed with the error message:
No extensions was provided as arguments, or found in 'config :my_app, :pow' configuration.

The readme was incorrect and I've updated it, thanks! You just have to run `mix pow_assent.phoenix.gen.templates`. Let me test locally here to see if I can replicate the issue.

**Comment by danschultzer** [comment]
Ok, so this was just another issue in the docs. I refactored it so it only passes the `conn` argument. If you update it to this it should work:

```elixir
def pow_assent_signed_in(conn),
  do: gettext("You've been signed in with %{provider}.", provider: Phoenix.Naming.humanize(conn.params["provider"]))
```

The readme has been updated, sorry for the confusion.

**Comment by jonathanraes** [comment]
That works, great. Thanks!
