### ISSUE TITLE
How is provider_link(conn, provider, providers_for_user) expected to be used?

### ISSUE THREAD

**Issue by dottjt** [danschultzer/pow_assent#48]
Hello!

I've seen this function, however I'm not exactly sure how `providers_for_user` is supposed to be populated, used? 

I understand what it does, but is there a variable which automatically tracks/populates it? In general is it just supposed to be an empty array?

Any help is greatly appreciated :)

**Comment by danschultzer** [comment]
You can find it in`PowAssent.Phoenix.ViewHelpers.provider_links/1` (which is the method I recommend using):

https://github.com/danschultzer/pow_assent/blob/ba2421fd96471b7950f6e63eefb3e865f1d3a75f/lib/pow_assent/phoenix/views/view_helpers.ex#L13-L20

You just have to call `PowAssent.Plug.providers_for_current_user(conn)` to get the providers for the user.

**Comment by dottjt** [comment]
Ah, okay. Excellent! 

Also just a quick one since you're here, but is it possible to test google sign in with localhost, or does it only work with a proper domain? I've setup the callbacks on Google developer console.

On localhost it returns a 401 once it gets the data and then returns back to localhost:
`%{"error" => "invalid_client", "error_description" => "Unauthorized"}`

I believe this is on GET /auth/google/callback

Just thought I'd ask :)

**Comment by danschultzer** [comment]
Yeah, localhost works with google, I've been testing it that way. The `invalid_client` means that Google didn't accept the client id.

**Comment by dottjt** [comment]
Ah okay, thank you very much!
