### ISSUE TITLE
user_identity schema bug

### ISSUE THREAD

**Issue by dottjt** [danschultzer/pow_assent#51]
Hey, thanks for the fix, however I believe there might be still some work (I believe this was an issue quite a while ago, only just realising now) :)

Essentially, I believe it has to do with the create_user_identities migration file.

This is what has been suggested to be used:
```
      add :user_id, references("users"), on_delete: :nothing
```

Full reference:
```
defmodule Nfd.Repo.Migrations.CreateUserIdentities do
  use Ecto.Migration

  def change do
    create table(:user_identities) do
      add :empty, :string
      add :provider, :string, null: false
      add :uid, :string, null: false

      add :user_id, references("users"), on_delete: :nothing

      timestamps(updated_at: false)
    end

    create unique_index(:user_identities, [:uid, :provider])
  end
end

```

However I get this error when creating the migrations:

<img width="509" alt="スクリーンショット 2019-03-26 午前8 00 52" src="https://user-images.githubusercontent.com/8922214/54953863-58d00b80-4f9d-11e9-99b2-97f5e2bc8536.png">

So what I did was change it to this a while ago:

`add :user_id, references(:users, on_delete: :nothing, type: :binary_id)`

and that fixes the error and now it will create the migration.

HOWEVER, I get this error from google when I go to register/sign in, and I believe it's related to this: 

<img width="508" alt="スクリーンショット 2019-03-26 午前7 58 58" src="https://user-images.githubusercontent.com/8922214/54953955-93d23f00-4f9d-11e9-9e61-7c64309f86ea.png">

I'm not sure what the correct syntax should be for the migration file for it to work.

**Comment by danschultzer** [comment]
Do you have `@foreign_key_type :binary_id` set in your user schema?

The mix task can't know in advance if the user schema is binary id or not, so you would have to run `mix pow_assent.install --binary-id` to make the right migration.

**Comment by danschultzer** [comment]
This is a pretty common scenario, I'm looking at the docs and code to see if it can be made more obvious how to set PowAssent up with binary id.

**Comment by dottjt** [comment]
Oh, thank you!

Just to clarify, but `add :user_id, references("users"), on_delete: :nothing` is the correct code for `create_user_identities`?

**Comment by dottjt** [comment]
Because I still get the same error with ecto.reset with that code

**Comment by dottjt** [comment]
```
defmodule Nfd.UserIdentities.UserIdentity do
  use Ecto.Schema
  use PowAssent.Ecto.UserIdentities.Schema,
    user: Nfd.Account.User

  @foreign_key_type :binary_id
  schema "user_identities" do
    pow_assent_user_identity_fields()

    timestamps(updated_at: false)
  end
end
```
is what I have.

**Comment by danschultzer** [comment]
> Just to clarify, but add :user_id, references("users"), on_delete: :nothing is the correct code for create_user_identities?

This is the correct migration (generated when running with the mix task with the `--binary-id` flag):

```elixir
add :user_id, references("users"), on_delete: :nothing, type: :binary_id
```

**Comment by dottjt** [comment]
Unfortunately that still produces the same error when ecto.migrate. Here are my files:

create_user_identities.exs

`defmodule Nfd.Repo.Migrations.CreateUserIdentities do
  use Ecto.Migration

  def change do
    create table(:user_identities) do
      add :empty, :string
      add :provider, :string, null: false
      add :uid, :string, null: false

      # add :user_id, references("users"), on_delete: :nothing, type: :binary_id
      add :user_id, references(:users, on_delete: :nothing, type: :binary_id)

      timestamps(updated_at: false)
    end

    create unique_index(:user_identities, [:uid, :provider])
  end
end
`


create_users.exs

`
defmodule Nfd.Repo.Migrations.CreateUsers do
  use Ecto.Migration

  def change do
    create table(:users, primary_key: false) do
      add :id, :binary_id, primary_key: true
      add :slug, :string
      add :display_name, :string
      add :first_name, :string
      add :last_name, :string
      add :is_admin, :boolean, default: false, null: false
      add :coaching_minutes, :integer

      add :email, :string, null: false
      add :password_hash, :string

      timestamps()
    end
    create unique_index(:users, [:email])

  end
end
`

User.ex

`
defmodule Nfd.Account.User do
  use Ecto.Schema
  use Pow.Ecto.Schema
  use Pow.Extension.Ecto.Schema,
    extensions: [PowResetPassword, PowEmailConfirmation]
  use PowAssent.Ecto.Schema

  import Ecto.Changeset

  alias Nfd.Account.Subscriber
  alias Nfd.Account.CollectionAccess

  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id
  schema "users" do
    has_many :user_identities,
      Nfd.UserIdentities.UserIdentity,
      on_delete: :delete_all

    pow_user_fields()

    field :coaching_minutes, :integer
    field :display_name, :string
    field :first_name, :string
    field :is_admin, :boolean, default: false
    field :last_name, :string
    field :slug, :string

    has_one :subscriber, Subscriber, on_delete: :delete_all
    has_many :collection_access, CollectionAccess, on_delete: :delete_all

    timestamps()
  end

  def changeset(user, attrs) do
    user
      |> pow_changeset(attrs)
      |> pow_extension_changeset(attrs)
  end

  def changeset_update(user, attrs) do
    user
    |> pow_changeset(attrs)
    |> pow_extension_changeset(attrs)
    |> cast(attrs, [:slug, :display_name, :first_name, :last_name, :is_admin, :coaching_minutes])
    |> validate_required([:slug, :display_name, :first_name, :last_name, :is_admin, :coaching_minutes])
  end

  # NOTE: This is unsafe and technically only for dev.
  def changeset_confirm_email(user, attrs) do
    user |> cast(attrs, [:email_confirmed_at])
  end
end

`

user_identity.ex

`
defmodule Nfd.UserIdentities.UserIdentity do
  use Ecto.Schema
  use PowAssent.Ecto.UserIdentities.Schema,
    user: Nfd.Account.User

  @foreign_key_type :binary_id
  schema "user_identities" do
    pow_assent_user_identity_fields()

    timestamps(updated_at: false)
  end
end

`

On the other hand, if I use 

`add :user_id, references(:users, on_delete: :nothing, type: :binary_id)`

Then the migration works, although Google sign in doesn't seem to work. I will do further testing to see what the cause my be, but I'm a bit stuck.

**Comment by dottjt** [comment]
Sorry for the poor formatting!

**Comment by dottjt** [comment]
Oh wait, everything seems to have worked successfully with:

`add :user_id, references(:users, on_delete: :nothing, type: :binary_id)`

Perhaps this is the correct syntax for the newer version of ecto?

**Comment by danschultzer** [comment]
Oh thanks a lot! It's a bug in Pow that I've overlooked. `add :user_id, references(:users, on_delete: :nothing, type: :binary_id)` is the right syntax.

So now with `@foreign_key_type :binary_id` and the right migration, does everything works as expected?

**Comment by dottjt** [comment]
Yes!

I already had @foreign_key_type :binary_id, so I'm actually a bit confused why it ended up working, given I already had `add :user_id, references(:users, on_delete: :nothing, type: :binary_id)` as an initial fix ages ago. But yeah, everything is working fine now :)

Thank you so much for your support, I'll be actively using the library and adding a few more, hopefully Facebook, Reddit and Discord over the coming weeks/months. I'll let you know if I run into anymore issues!

**Comment by dottjt** [comment]
Oh, and I didn't know ``` would fix the formatting, I will remember for next time :)

**Comment by danschultzer** [comment]
`1.0.5` is released now with bug fix!
