### ISSUE TITLE
Uses incorrect clientId in prod

### ISSUE THREAD

**Issue by dottjt** [danschultzer/pow_assent#57]
Hey! 

I'm having a weird issue where when you try and login using Google sign in, it throws an error saying that the redirect doesn't work.

Then it references this client_id 954591220445-1l03q4c08vdci34g8tdcjcgp134 which is really odd, because I can't see it ANYWHERE at all within the codebase, nor within the .env files or even within the head.html when you inspect the source. 

Any possible idea why this might be happening?

**Comment by dottjt** [comment]
You can also try here: https://neverfapdeluxe.com/session/new

**Comment by dottjt** [comment]
Oh wait, I may possibly have resolved this, please ignore for a few days. I didn't configure the redirect url for http:// (only https) although it still doesn't explain why the client id is completely different, although perhaps that's referring to another client id?

**Comment by danschultzer** [comment]
Google sign in is not very verbose, but yeah, most likely it's the redirect setting that's missing/wrong.

**Comment by dottjt** [comment]
Thanks for responding. I'll leave it for a day, because I know last time I changed the redirect settings it took a while for them actually to get into affect, however it's just very odd.

**Comment by dottjt** [comment]
I thought I'd update this ticket. So with the callback url setup correctly, it will now connect, however I get this error now:
```
nfd-app    | Body:
nfd-app    | %{"error" => "invalid_client", "error_description" => "Unauthorized"}
nfd-app    |
nfd-app    |         (pow_assent) lib/pow_assent/phoenix/controllers/authorization_controller.ex:186: PowAssent.Phoenix.AuthorizationController.handle_strategy_error/1
nfd-app    |         (pow) lib/pow/phoenix/controllers/controller.ex:100: Pow.Phoenix.Controller.action/3
nfd-app    |         (pow_assent) lib/pow_assent/phoenix/controllers/authorization_controller.ex:1: PowAssent.Phoenix.AuthorizationController.action/2
nfd-app    |         (pow_assent) lib/pow_assent/phoenix/controllers/authorization_controller.ex:1: PowAssent.Phoenix.AuthorizationController.phoenix_controller_pipeline/2
```

But I still can't quite figure out why it's working on develop correctly, when it's not working on prod. Will investigate further.

**Comment by dottjt** [comment]
Okay, so I may possibly have figured it out. In my .env file the code was something like this:
```
GOOGLE_CLIENT_SECRET= XXXXXXXXXX
```
I think that space may be why it's not been working. Will confirm.

**Comment by dottjt** [comment]
Okay, so it turned out the issue is with my database, and now it's fully working.

For whatever reason, 'ecto.migrate' has never worked on prod inside my dockerfile, and so user_identities was never created. So essentially, the below command doesn't work inside a dockerfile. I'm not quite sure how to make it work, but I essentially copied the sql user_identities table from dev and put into prod via GUI.

`CMD ["mix", "do", "ecto.create,", "ecto.migrate,", "run priv/repo/seeds.exs,", "phx.server"]`

Sorry for all the commotion!

**Comment by danschultzer** [comment]
I'm not sure that works in production if you e.g. make the build with distillery. I use distillery, and use this to run migrations in production: https://github.com/bitwalker/distillery/blob/master/docs/guides/running_migrations.md

You will probably experience migration issues in the future by manually modifying the db, so I recommend that you reverse the change, and run the migration.

**Comment by dottjt** [comment]
Unfortunately I had issue getting distillery to run with docker, so I'm currently using the elixir docker image. 

But yeah, still haven't figured out a way to run commands inside the docker container while it's running. What I've attempted with the Docker file is to run the app via `iex -S` however it still doesn't allow you access to the command line when you connect to the container running in a daemon. 

Ah well, it's good enough for now. Unfortunately I have a million other priorities atm.

**Comment by danschultzer** [comment]
Oh, I see. Yeah, better to prioritize what's actually important atm.

In case you ever get back to it, I did write a full CI production deployment setup guide with distillery (using ansible to automate the builds and deploy): https://dreamconception.com/tech/phoenix-automated-build-and-deploy-made-simple/
