### ISSUE TITLE
Update user identity with new access token or fresh token

### ISSUE THREAD

**Issue by danschultzer** [danschultzer/pow_assent#69]
With #66 it's possible to capture and store access and refresh tokens from the provider. However, when re-authenticating no update method call is used since `:provider` and `:uid` are permanent values and only [`PowAssent.Ecto.UserIdentities.Context. get_user_by_provider_uid/3`](https://github.com/danschultzer/pow_assent/blob/55697f94b7ad2bc05e9da5adedb65d67980f3a69/lib/pow_assent/ecto/user_identities/context.ex#L101-L114) is called.

The user identities table is built with just create and delete in mind. No update calls. This makes sense since authorization happens once. With custom access and refresh token it's different though. The authorization happens, but there may be additional information that needs to be updated.

Maybe the row should be deleted and created again if there's any changes to the changeset? Not sure what makes sense here.

**Comment by blatyo** [comment]
Instead of doing the find or create pattern, I would do upsert. If it's a new record, it gets inserted. If it's an existing record, it conflicts on uniqueness of provider and uid and updates the new values. Something like:

``` elixir
def upsert_user_identity(params) do
  %UserIdentity{}
  |> UserIdentity.changeset(params)
  |> Repo.insert(conflict_target: [:uid, :provider], on_conflict: : replace_all_except_primary_key)
end
```

> This makes sense since authorization happens once.

I'd argue that isn't true. You're authorized for a period of time.

**Comment by danschultzer** [comment]
Excellent suggestion, that makes a lot of sense. I also agree that authorization should be seen as temporary. I'll see how I can refactor the flow so upsert is used for identity.

**Comment by danschultzer** [comment]
Got it up and running in #79. I'll just have to do a few manual tests to ensure this works, and then it'll be merged to master.
