### ISSUE TITLE
Use ecto to handle upsert

### ISSUE THREAD

**Issue by danschultzer** [danschultzer/pow_assent#78]
Per discussion in #76 there may be a way to let the DB handle the upsert:

> I believe the proper way to do this is to include a where clause in the on_conflict option. The way to do that is to pass a query to on_conflict in ecto. I think this would achieve that. Though, I haven't run this code, so not sure how it'd behave.
>
> ``` elixir
> updates = Enum.reject(changeset.changes, fn {key, _} -> key == :id end)
> on_conflict = 
>   from(ui in UserIdentity, 
>     where: ui.user_id == ^(user.id),
>     update: [set: updates]
> Repo.insert(changeset, conflict_target: [:uid, :provider], on_conflict: on_conflict)
> ```

_Originally posted by @blatyo in https://github.com/danschultzer/pow_assent/pull/76_

**Comment by danschultzer** [comment]
Tested this, but it doesn't work with stale insert error:

```
$ mix test test/pow_assent/ecto/user_identities/context_test.exs:119

Excluding tags: [:test]
Including tags: [line: "119"]

  1) test upsert/3 when other user has provider uid (PowAssent.Ecto.UserIdentities.ContextTest)
     test/pow_assent/ecto/user_identities/context_test.exs:113
     ** (Ecto.StaleEntryError) attempted to insert a stale struct:
     
     %PowAssent.Test.Ecto.UserIdentities.UserIdentityWithAccessToken{__meta__: #Ecto.Schema.Metadata<:built, "user_identities">, access_token: nil, id: nil, inserted_at: nil, provider: nil, refresh_token: nil, uid: nil, updated_at: nil, user: #Ecto.Association.NotLoaded<association :user is not loaded>, user_id: 1}
```

I'm not really sure why there's no provider or uid set as well. For reference this is what `upsert/3` now looks like:

```elixir
  @spec upsert(user(), user_identity_params(), Config.t()) :: {:ok, user_identity()} | {:error, {:bound_to_different_user, changeset()}} | {:error, changeset()}
  def upsert(user, user_identity_params, config) do
    params        = convert_params(user_identity_params)
    user_identity = Ecto.build_assoc(user, :user_identities)

    changeset =
      user
      |> Ecto.build_assoc(:user_identities)
      |> user_identity.__struct__.changeset(params)

    updates       = Enum.reject(changeset.changes, fn {key, _} -> key == :id end)
    on_conflict   = user_identity.__struct__ |> where([ui], ui.user_id == ^user.id) |> update(set: ^updates)
    repo_opts     = Config.get(config, :repo_opts, []) ++ [conflict_target: [:uid, :provider], on_conflict: on_conflict]
    config        = Config.put(config, :repo_opts, repo_opts)

    changeset
    |> Context.do_insert(config)
    |> case do
      {:error, %{errors: [uid_provider: _]} = changeset} ->
        {:error, {:bound_to_different_user, changeset}}

      {:ok, user_identity} ->
        {:ok, user_identity}
    end
  end
```

Probably not necessary with the `Enum.reject` since `:id` wouldn't be changed anyway.

**Comment by blatyo** [comment]
I put id in there because I wasn't sure if in the case of binary id where ecto generates it, it would be present. I was actually sort of expecting you'd get `nil` back from `insert` with these changes. I'll play around with this on the weekend. I suspect this is actually working database wise, but there may not be a good way to surface the error in ecto in a way that makes sense.

**Comment by danschultzer** [comment]
Yeah, I think you may be right. I got a some other things to deal with so I'll wait till the weekend to check up on this again. Thanks for the help!

Also, I think binary id is handled in repo insert, but it may be a good idea to filter out `:id` (and probably `:user_id`) since a developer may inadvertently set it in their custom changeset.

**Comment by blatyo** [comment]
I think this can be closed. I've tried some thing and don't think upsert can be used here effectively.

**Comment by danschultzer** [comment]
Yeah, I came to the same conclusion, too bad. Thanks for trying it out 👍

`v0.3.1` is out and upserts the user identity.

**Comment by blatyo** [comment]
thanks
