### ISSUE TITLE
Associate existing Email to a Github account

### ISSUE THREAD

**Issue by popo63301** [danschultzer/pow_assent#79]
Hello !

I'm trying out this library so I made a signup form with email and a Github login. Both methods works great separately. My problem is when I create an account with an email (say: my_email@gmail.com) and then I want to connect with Github with an account that has the same email, they ask me to  Register with an other email because the email `has already been taken`. However, the behavior I want is to associate my Github account to my existing email account.

Is this a normal behavior of the library?

**Comment by stuartbain** [comment]
Hi @popo63301,

Check out https://github.com/danschultzer/pow_assent/issues/18 which Dan helped me out with the same question.

Stuart

**Comment by popo63301** [comment]
Indeed, I haven't seen this issue before. Thanks @stuartbain !

Nevertheless, I wonder why it isn't the normal behavior for Pow Assent.

**Comment by danschultzer** [comment]
> Nevertheless, I wonder why it isn't the normal behavior for Pow Assent.

It’s for security. Some providers may make it possible to sign up without confirming email, and that could then be used to gain access to an account on your platform through PowAssent.

So I think it’s better to force developers to set it up themselves so they can take adequate steps to secure their platform.

**Comment by popo63301** [comment]
I understand now. Thanks @danschultzer  !
