### ISSUE TITLE
Not keeping session

### ISSUE THREAD

**Issue by Kaquadu** [danschultzer/pow_assent#84]
Hi,
I'm currently trying to create signing in via Google and Facebook for users in my app. I followed installation and setup guide, however when I'm trying to sign in - my app creates an account with details from provider, but it doesn't keep session params in `conn`. I'm just still logged out. To cache I'm using Mnesia.

`config.exs`
```
...
config :base_app, :pow,
  user: BaseApp.Auth.User,
  repo: BaseApp.Repo,
  extensions: [PowResetPassword, PowEmailConfirmation],
  controller_callbacks: Pow.Extension.Phoenix.ControllerCallbacks,
  mailer_backend: BaseAppWeb.Mailer
...
```

`endpoint.ex`
```
...
plug Pow.Plug.Session,
    otp_app: :base_app,
    repo: BaseApp.Repo,
    user: BaseApp.Auth.Admin,
    current_user_assigns_key: :current_admin,
    session_key: "admin_auth",
    cache_store_backend: Pow.Store.Backend.MnesiaCache
  
  plug Pow.Plug.Session,
    otp_app: :base_app,
    repo: BaseApp.Repo,
    user: BaseApp.Auth.User,
    cache_store_backend: Pow.Store.Backend.MnesiaCache,
    current_user_assigns_key: :current_user

  plug BaseAppWeb.Router
```

`:plug_session` from `conn.private` after trying to sign in:
```
:plug_session => %{
      "_csrf_token" => "some_code",
      "admin_auth" => "base_app_some_code",
      "base_app_auth" => "base_app_some_code",
      "phoenix_flash" => %{"info" => nil},
      "pow_assent_session_params" => nil
    },
```

I will really appreciate any advice.

**Comment by danschultzer** [comment]
Looks like the session keys are set in `:plug_session`. Is it `:current_admin`, `:current_user` or both that doesn't work?

**Comment by danschultzer** [comment]
Also you can refactor the above:

```elixir

# config/config.exs

config :base_app, :pow,
  user: BaseApp.Auth.User,
  repo: BaseApp.Repo,
  extensions: [PowResetPassword, PowEmailConfirmation],
  controller_callbacks: Pow.Extension.Phoenix.ControllerCallbacks,
  mailer_backend: BaseAppWeb.Mailer,
  cache_store_backend: Pow.Store.Backend.MnesiaCache,

# endpoint.ex

  plug Pow.Plug.Session,
    otp_app: :base_app,
    user: BaseApp.Auth.Admin,
    current_user_assigns_key: :current_admin,
    session_key: "admin_auth"
  
  plug Pow.Plug.Session, otp_app: :base_app

  plug BaseAppWeb.Router
````

The `otp_app: :base_app` will ensure that if a config option is not found in the passed config, it'll fallback to the `config :base_app, :pow` config

**Comment by Kaquadu** [comment]
Yeah, you're right - session keys should be stored in `:plug_session`. I've got separate data tables for user and admin role. That is why there is `:current_user` and `:current_admin` - and when it comes to logging in via username and password everything worked fine, current user is stored in `:plug_session`. 

Your solution from second post works for me! Thank you very much! 🥇
