### ISSUE TITLE
Alter :user_name and :email if auth fails?

### ISSUE THREAD

**Issue by mitkins** [danschultzer/pow_assent#90]
I’ve been playing around with GitHub authentication. When I added `PowAssent` to my `Pow` configuration, I was unable to register my GitHub account. That’s because I had created an account using my real email address when testing Pow. 

Reading other issues here - that makes sense (you can’t tie an auth method unless you're signed in). If registration failed, the default behaviour is to show the Register page - where you can create your own `:user_name`. 

However, for my app I need a unique `:user_name` and `:email`. So I altered the Register template to include the email address:

```elixir
<h3>Register</h3>

<%= form_for @changeset, @action, [as: :user], fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, Pow.Ecto.Schema.user_id_field(@changeset) %>
    <%= text_input f, Pow.Ecto.Schema.user_id_field(@changeset), class: "form-control" %>
    <%= error_tag f, Pow.Ecto.Schema.user_id_field(@changeset) %>
  </div>

  <div class="form-group">
    <label>Email</label>
    <%= text_input f, :email, class: "form-control" %>
    <%= error_tag f, :email %>
  </div>

  <div class="form-group">
    <%= submit "Register", class: "btn btn-outline-secondary" %>
  </div>
<% end %>
```

When I go to this page, both fields are empty. Is there a way for me to pre-populate the fields with the values from GitHub (as a starting point)? Also, if there are default values it would be nice if it could display which field(s) violated the unique constraint - so the user can focus on what alternative they may provide.

Is there a way to do this?

**Comment by danschultzer** [comment]
Yeah, take a look at this: https://github.com/danschultzer/pow_assent#populate-fields

Since you have username as your user id field, you'll need to cast the `:email`. Also you'll have to cast the `nickname` in the Github `attrs` as username. This is how you can do that:

```elixir
defmodule MyApp.Users.User do
  use Ecto.Schema
  use Pow.Ecto.Schema
  use PowAssent.Ecto.Schema

  # ...

  def user_identity_changeset(user_or_changeset, user_identity, attrs, user_id_attrs) do
    user_or_changeset
    |> cast_email(attrs, user_id_attrs)
    |> put_username(attrs)
    |> pow_assent_user_identity_changeset(user_identity, attrs, user_id_attrs)
  end

  defp cast_email(changeset, attrs, user_id_attrs) do
    changeset
    |> Ecto.Changeset.cast(attrs, [:email])
    |> Ecto.Changeset.cast(user_id_attrs, [:email]) # Make sure that we cast user input last to override the one fetched from Github
  end

  defp put_username(changeset, %{"nickname" => username}), do: Ecto.Changeset.put_change(changeset, :username, username)
  defp put_username(changeset, _attrs), do: changeset
end
```

FYI, the `user_id_attrs` is what's submitted by the user with the above form, while `attrs` is what's received by the provider. The latter can be trusted, while the former may need additional validation.

The above isn't tested, but this is more a less how it should work. Please add appropriate unit tests for this. I think this could be great as a guide too on https://powauth.com/guides/ so please submit any changes the code need to work or unit test you added 😄

**Comment by mitkins** [comment]
So I was thinking that I would add something like [this](https://github.com/mitkins/pow_assent/commit/2b92fb894bda21e9a7229c7fdcb3a7e7139d7fe1) (based on the code above) and perhaps a unit test like this (a copy and paste job):

```
defmodule PowAssent.Phoenix.CustomUserAuthorizationControllerTest do
  use PowAssent.Test.Phoenix.ConnCase

  import PowAssent.Test.TestProvider, only: [expect_oauth2_flow: 2, put_oauth2_env: 1, put_oauth2_env: 2]

  alias PowAssent.Test.{Ecto.Users.CustomUser, UserIdentitiesMock}

  @provider "test_provider"
  @callback_params %{code: "test", redirect_uri: "", state: "token"}

  setup _context do
    user   = %CustomUser{id: :loaded}
    bypass = Bypass.open()

    put_oauth2_env(bypass)

    {:ok, user: user, bypass: bypass}
  end

  describe "GET /auth/:provider/callback" do
    setup %{conn: conn} do
      conn = Plug.Conn.put_session(conn, :pow_assent_session_params, %{state: "token"})

      {:ok, conn: conn}
    end

    test "when identity doesn't exist and missing user id", %{conn: conn, bypass: bypass} do
      expect_oauth2_flow(bypass, user: %{email: ""})

      conn = get conn, Routes.pow_assent_authorization_path(conn, :callback, @provider, @callback_params)

      assert redirected_to(conn) == Routes.pow_assent_registration_path(conn, :add_user_id, "test_provider")
      assert %{"test_provider" => %{user_identity: user_identity, user: user}} = Plug.Conn.get_session(conn, :pow_assent_params)
      assert user_identity == %{"provider" => "test_provider", "uid" => "new_user", "token" => %{"access_token" => "access_token"}}
      assert user == %{"name" => "Dan Schultzer", "email" => ""}
      refute Plug.Conn.get_session(conn, :pow_assent_session_params)
    end
  end
end
```

But it's only a guess (based on not much experience) at what I should do. Sorry to be a pain, but if you can provide some tips, I'm happy to help

**Comment by danschultzer** [comment]
In this case you would need to unit test the `user_identity_changeset/4` method directly, rather than using a controller test. Also the changeset method can be made simpler, since you can rely on the the `pow_assent_user_identity_changeset/4` method for the user id field. I’ll post a refactored version tomorrow.

**Comment by mitkins** [comment]
Ah, I forgot to mention. In my project, if it violates a unique constraint (for `:email` and/or `:user_name`) it dumps the user to the login page with an error message - instead of redirecting to the Register page. I was hoping to create a test for that scenario too.

**Comment by danschultzer** [comment]
Actually, your code was pretty good, just a few things I would change:

1. The changeset should also have email validation if email can be changed or users can sign up with just password
2. `Ecto.Changeset.unique_constraint(:user_name, on: User.Repo)` isn't necessary since the user id field already have unique constraint check in Pow
3. Cast before pow changeset calls, and custom validate after

```elixir
defmodule PowAssent.Test.Ecto.Users.CustomUser do
  @moduledoc false
  use Ecto.Schema
  use Pow.Ecto.Schema, user_id_field: :user_name
  use PowAssent.Ecto.Schema

  schema "users" do
    field :user_name, :string
    field :name, :string

    pow_user_fields()

    timestamps()
  end

  def changeset(user_or_changeset, attrs) do
    user_or_changeset
    |> pow_changeset(attrs)
    |> validate_name(attrs)
    |> validate_email(attrs)
  end

  def user_identity_changeset(user_or_changeset, user_identity, attrs, user_id_attrs) do
    user_or_changeset
    |> put_username_from_uid(attrs)
    |> Ecto.Changeset.cast(user_id_attrs, :email)
    |> pow_assent_user_identity_changeset(user_identity, attrs, user_id_attrs)
    |> validate_name(attrs)
    |> validate_email(attrs)
  end

  defp validate_name(user_or_changeset, attrs) do
    user_or_changeset
    |> Ecto.Changeset.cast(attrs, [:name])
    |> Ecto.Changeset.validate_required([:name])
  end
  
  defp validate_email(user_or_changeset, attrs) do
    user_or_changeset
    |> Ecto.Changeset.cast(attrs, [:email])
    |> Ecto.Changeset.validate_required([:email])
    |> Ecto.Changeset.unique_constraint([:email])
  end
  
  defp put_username_from_uid(changeset, %{"uid" => user_name}), do: Ecto.Changeset.put_change(changeset, :user_name, user_name)
  defp put_username_from_uid(changeset, _attrs), do: changeset
end
```

The email format isn't validated. You can use https://hexdocs.pm/pow/Pow.Ecto.Schema.Changeset.html#validate_email/1 if you want to depend on Pow for that.

**Comment by mitkins** [comment]
I'm still working on my tests. But I've confirmed the code path that results in the redirect to the login page (instead of the register page). Given the `CustomUser` structure (above), `:email` isn't the primary id, but it also needs to be unique.

In `PowAssent.Ecto.UserIdentities.Context` there's the `create_user` function:

```
  def create_user(user_identity_params, user_params, user_id_params, config) do
    params        = convert_params(user_identity_params)
    user_mod      = user!(config)
    user_id_field = user_mod.pow_user_id_field()

    user_mod
    |> struct()
    |> user_mod.user_identity_changeset(params, user_params, user_id_params)
    |> Context.do_insert(config)
    |> case do
      {:error, %{changes: %{user_identities: [%{errors: [uid_provider: _]}]}} = changeset} ->
        {:error, {:bound_to_different_user, changeset}}

      {:error, %{errors: [{^user_id_field, _}]} = changeset} ->
        {:error, {:invalid_user_id_field, changeset}}

      {:error, changeset} ->
        {:error, changeset}

      {:ok, user} ->
        {:ok, user}
    end
  end
```

Because `:user_name` is the `user_id_field` - the 2nd case never matches for the `:email` field. It just falls through to the generic error handler (which, later on, redirects to the login page). If I add the following code (to trap any unique constraint) - then the redirect goes to the Register page:

```
      {:error, %{errors: [{_field, {_desc, [constraint: :unique, constraint_name: _constraint_name]}}]} = changeset} ->
        {:error, {:invalid_user_id_field, changeset}}
```

Just thought I'd mention it - I'll attempt to make a unit test for this now that I know exactly what's happening.

**Comment by danschultzer** [comment]
Good call!

A way to handle it currently would be to set up a custom context so you can catch the :email validation failure in a custom `create_user/2`: https://github.com/danschultzer/pow_assent/blob/v0.3.2/lib/pow_assent/ecto/user_identities/context.ex#L11-L22

```elixir
defmodule MyApp.UserIdentities do
  use PowAssent.Ecto.UserIdentities.Context,
    repo: MyApp.Repo,
    user: MyApp.Users.User

  def create_user(user_identity_params, user_params, user_id_params)
    user_identity_params
    |> pow_assent_create_user(user_params, user_id_params)
    |> case do
      {:error, %{errors: [{:email, _}]} = changeset} ->
        {:error, {:invalid_user_id_field, changeset}}

      any ->
        any
    end
  end
end
```

I'll review the codebase if there an easier way to deal with it.

**Comment by mitkins** [comment]
As an idea, I was thinking potentially you could have another config field called `secondary_field`. Any errors on this field could be trapped (just like `user_id_field`). 

You could also add a conditional section in the default Register template to accommodate a `secondary_field`.

**Comment by mitkins** [comment]
Getting back to the original question. I implemented your workaround (above) successfully. The register page shows, but `:user_name` and `:email` are empty. So I implemented the following workaround in my template:

```html
<h3>Register</h3>

<%
  changeset = @changeset

  changeset = if !Ecto.Changeset.get_change(changeset, :email) do
    Ecto.Changeset.put_change( changeset, :email, @conn.private.pow_assent_params.user["email"] )
  else
    changeset
  end

  changeset = if !Ecto.Changeset.get_change(changeset, :user_name) do
    Ecto.Changeset.put_change( changeset, :user_name, @conn.private.pow_assent_params.user["nickname"] )
  else
    changeset
  end
%>

<%= form_for changeset, @action, [as: :user], fn f -> %>
  <%= if changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, Pow.Ecto.Schema.user_id_field(@changeset) %>
    <%= text_input f, Pow.Ecto.Schema.user_id_field(@changeset), class: "form-control" %>
    <%= error_tag f, Pow.Ecto.Schema.user_id_field(@changeset) %>
  </div>

  <div class="form-group">
    <label>Email</label>
    <%= text_input f, :email, class: "form-control" %>
    <%= error_tag f, :email %>
  </div>

  <div class="form-group">
    <%= submit "Register", class: "btn btn-outline-secondary" %>
  </div>
<% end %>
```

Which looks like all sorts of bad to me. But is the only way I could think of to achieve what I want. 

The workflow isn't bad either:

* The first time you come to the register page - it just shows the `:user_name` and `:email` without explaining that anything went wrong
* The user can just click the "Register" button without typing anything
* **Now** they can see what's wrong, and make adjustments

**Comment by danschultzer** [comment]
>  The register page shows, but `:user_name` and `:email` are empty.

Yeah, it's because I [use a blank changeset](https://github.com/danschultzer/pow_assent/blob/d6ca64b56ee1761e8fd48759b47c5415104f1b2d/lib/pow_assent/phoenix/controllers/registration_controller.ex#L12-L22) since by default there is only one field and we already know that the value can't be used, and the page already explains that.

You can make it much simpler by just setting `value: Ecto.Changeset.get_change(@changeset, :email, default_value)` for the inputs. To make it easier to read I've just add the variables to the top:

```elixir
<h3>Register</h3>

<%
  default_user_id = @conn.private.pow_assent_params.user["nickname"]
  default_email = @conn.private.pow_assent_params.user["email"]

  user_id = Ecto.Changeset.get_change(@changeset, Pow.Ecto.Schema.user_id_field(@changeset), default_user_id)
  email = Ecto.Changeset.get_change(@changeset, :email, default_email)
%>

<%= form_for changeset, @action, [as: :user], fn f -> %>
  <%= if changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, Pow.Ecto.Schema.user_id_field(@changeset) %>
    <%= text_input f, Pow.Ecto.Schema.user_id_field(@changeset), value: user_id, class: "form-control" %>
    <%= error_tag f, Pow.Ecto.Schema.user_id_field(@changeset) %>
  </div>

  <div class="form-group">
    <label>Email</label>
    <%= text_input f, :email, value: email, class: "form-control" %>
    <%= error_tag f, :email %>
  </div>

  <div class="form-group">
    <%= submit "Register", class: "btn btn-outline-secondary" %>
  </div>
<% end %>
```

**Comment by mitkins** [comment]
Thanks for the tip! I'll just go with the above then!
